services:
  ui:
    image: index.docker.io/kieranwifinitive/zimvest-mining:latest
    container_name: zimvest
    env_file:
      - ./.env
    restart: always
  web_server:
    image: nginx
    container_name: zimvest_webserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
